name: your_project_name
description: A new Flutter project.

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  marquee: ^2.2.1  # â† Moved marquee here


flutter_icons:
  android: true
  ios: true
  image_path: "android/app/src/main/res/logo.png"
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/ewit.jpg
    - images/sv.jpg
    - images/tby.jpg
    - images/th.jpg
    - images/b.jpg
    - images/f.jpg
    - images/am.jpg
    - images/micro.jpg
    - images/quran.jpg
    - images/murder.jpg
    - images/1.jpg
    - images/2.jpg
    - images/3.jpg
    - images/4.jpg
    - images/5.jpg
    - images/6.png
    - images/7.jpg
    - images/8.jpg